### ISSUE TITLE
CAN Socket Optimization

### ISSUE THREAD

**Issue by superdan-t** [BinghamtonRover/BurtOS-2#11]
Instead of opening and closing the socket with each send, save the open socket and reuse it after initialization.

**Comment by jmcmah10** [comment]
-Allow CAN messages to be sent and constructed without using char* to construct them
-Create enums for the devices and commands

**Comment by superdan-t** [comment]
I didn't close this issue with the pull request since it sounds like there's more optimization to do. However, if you keep working on this issue, I'd start a new branch from main.
