### ISSUE TITLE
Additional video streaming features

### ISSUE THREAD

**Issue by superdan-t** [BinghamtonRover/BurtOS-2#29]
## Requirements
The old video streaming program has been ported to `src/video/`. We want to support some new features when streaming:
* Keep settings separate for each stream. Currently, the JPEG quality and grayscale options apply globally. Change the functionality so that each stream has its own settings. Make sure to update the network messages in `src/network/rover_system_messages/` and handlers in the video computer so we can change the settings remotely.
* Add an option to change video resolution and framerate for each stream remotely
* Any refactoring is also welcome. The video computer was written a few years ago and may not reflect our new goals and programming style.

### Future Requirements
Open a PR for the requirements above first, but we want to work towards the following features.
* Giving string names to streams
* Identifying specific cameras based on serial number, name, interface name, or other unique info available

**Comment by Levi-Lesches** [comment]
Closing this in favor of rewriting much of the system in BinghamtonRover/network#1
