### ISSUE TITLE
Errors when setting or changing multicast address with GUI

### ISSUE THREAD

**Issue by superdan-t** [BinghamtonRover/BurtOS-2#50]
If the subsystem multicast feed is configured using the Network Settings menu on a Linux system, the socket will break. This does not happen on Windows. The error appears unrelated to the GUI, but more investigation is needed. For now, this is resolved by setting the feed endpoint as a constant in the `Basestation` constructor as it initializes correctly. An unknown event in between the constructor and the menu causes problems.

**Comment by Levi-Lesches** [comment]
This issue is related to sockets, which means it'll probably need to be retested after BinghamtonRover/network#1
