### ISSUE TITLE
CAN Refactoring

### ISSUE THREAD

**Issue by jmcmah10** [BinghamtonRover/BurtOS-2#66]
Some last second changes were made to CAN bus on the subsystem that left the codebase with some unnecessary methods, and hard to read code. These methods should be removed, and the existing code should be rewritten to be more legible and scalable.

**Comment by superdan-t** [comment]
The CAN socket is opened twice:
https://github.com/BinghamtonRover/BurtOS-2/blob/main/src/subsystem/subsystem.cpp#L119

Not sure how that slipped by but this issue is a good place to fix it
