### ISSUE TITLE
Network library refactoring and minor fixes

### ISSUE THREAD

**Issue by superdan-t** [BinghamtonRover/BurtOS-2#67]
## Objectives
* Review the network library to ensure the interface is consistent and functional
* Fix #50
* Other small organizational changes

## Timeline
This should be a short issue.
GanttStart: 2022-03-26
GanttDue: 2022-04-12

**Comment by superdan-t** [comment]
I am pausing this issue since it is a "nice to have" and there are more important things to work on right now. I'm pushing the due date by 2 weeks.

**Comment by Levi-Lesches** [comment]
Closing in favor of BinghamtonRover/network#1
