### ISSUE TITLE
Concurrent video feeds

### ISSUE THREAD

**Issue by superdan-t** [BinghamtonRover/BurtOS-2#68]
Continuation of #9. Add support to decode multiple video streams concurrently and switch between them.

Branch from `albertson_9` and merge back into that branch on completion. Then, #62 will be ready to merge into main for the completion of both tasks.

GanttStart: 2022-03-31
GanttDue: 2022-04-04

**Comment by superdan-t** [comment]
Create a VideoControl class as a part of the `rover_control` library. Video control needs these features:
* Send/receive network messages to control the video computer
* Propagate decoded frames to generic new frame handlers.
    * Track the subscriber count on each stream and close the stream if it reaches 0
* Create/destroy the TurboJPEG decoder
  * Use a separate decoding thread
* Use conditional compilation to allow using `rc::VideoControl` even when TurboJPEG is not present. All functionality should be present, except trying to subscribe to the decoder output should produce an error.

**Comment by Levi-Lesches** [comment]
Closing since we've moved to Flutter. See https://github.com/BinghamtonRover/rover-control-dashboard/issues/16
