### ISSUE TITLE
Video feed GUI menus

### ISSUE THREAD

**Issue by superdan-t** [BinghamtonRover/BurtOS-2#69]
Make sure all of these can be configured using the GUI:
* Changing network stream settings for video. Add this to the network menu, which is already a module.
* Switching the stream displayed in the video player. Make sure that any streams which are not in use are switched off.

GanttStart: 2022-04-04
GanttDue: 2022-04-08

**Comment by Levi-Lesches** [comment]
Closing as duplicates of: 
- Network settings: https://github.com/BinghamtonRover/rover-control-dashboard/issues/19
- Configurable streams: https://github.com/BinghamtonRover/rover-control-dashboard/issues/16
